Demo: MultiClassTsetlinMachine.c MultiClassTsetlinMachine.h TsetlinMachine.c TsetlinMachine.h Demo.c
	gcc -W  -O3 -ffast-math -o a Demo.c MultiClassTsetlinMachine.c TsetlinMachine.c 

clean:
	rm *.o Demo
