Demo: MultiClassTsetlinMachine.c MultiClassTsetlinMachine.h TsetlinMachine.c TsetlinMachine.h NoisyXORDemo.c
	gcc -Wall -O3 -ffast-math -o a Demo.c MultiClassTsetlinMachine.c TsetlinMachine.c 

clean:
	rm *.o Demo
